image: Visual Studio 2017
cache:
- .paket -> paket.lock
- packages -> paket.lock

before_build:
- ps: dotnet restore

configuration: Release
platform: Any CPU

build:
  verbosity: minimal

on_failure:
  - ps: Get-ChildItem $env:temp\*.png | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
