pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'

steps:

- task: VSBuild@1
  displayName: Build
  inputs:
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/restore'

- task: VSTest@2
  inputs:
    configuration: '$(buildConfiguration)'